<<<<<<< HEAD
<<<<<<< HEAD
port: 8100
OutputPath: /tmp/
BBBPresPath: /var/bigbluebutton/
ScriptDir: /usr/share/bbb-api-pyscript/
EventsPath: /var/bigbluebutton/
FontPath: /home/taktak/Desktop/bigbluebutton-annotations-api-server/font/
||||||| parent of bd6f49b (- Add Vagrant configuration for dev.)
port: :8100
TempPath: /tmp/
BBB: /var/bigbluebutton/
=======
||||||| parent of ddf7b04 (config + post + write text + arabic + optimization)
=======
<<<<<<< HEAD
>>>>>>> ddf7b04 (config + post + write text + arabic + optimization)
port: 8100
OutputPath: /var/bigbluebutton/inbox/
BBBPresPath: /var/bigbluebutton/
<<<<<<< HEAD
>>>>>>> bd6f49b (- Add Vagrant configuration for dev.)
||||||| parent of ddf7b04 (config + post + write text + arabic + optimization)
=======
||||||| parent of 2c42ff1 (config + post + write text + arabic + optimization)
port: :8100
TempPath: /tmp/
BBB: /var/bigbluebutton/
=======
port: 8100
OutputPath: /tmp/
BBBPresPath: /var/bigbluebutton/
ScriptDir: /usr/share/bbb-api-pyscript/
EventsPath: /var/bigbluebutton/
FontPath: /home/taktak/Desktop/bigbluebutton-annotations-api-server/font/
>>>>>>> 2c42ff1 (config + post + write text + arabic + optimization)
>>>>>>> ddf7b04 (config + post + write text + arabic + optimization)
