port: 8100
OutputPath: /tmp/
BBBPresPath: /var/bigbluebutton/
ScriptDir: /usr/share/bbb-api-pyscript/
EventsPath: /var/bigbluebutton/
FontPath: /home/taktak/Desktop/bigbluebutton-annotations-api-server/font/